#!/bin/bash

qemu-system-aarch64 \
    -net nic \
    -net user \
    -enable-kvm \
    -cpu host \
    -machine virt \
    -m 1G \
    -kernel "vmlinuz" \
    -initrd "initrd" \
    -nographic \
    -append "console=ttyAMA0" \
    -drive file=hda.disk,format=raw,index=0,media="disk"
    

#-smbios type=1,serial=ds='nocloud;s=http://10.0.2.2:8000/'
